# Category.new(title: "Personal Story")
# Category.new(title: "Learning to Code")
# Category.new(title: "Happiness and Success")
# Category.new(title: "Trying New Things")
# Category.new(title: "Coding Tips")
# Category.new(title: "Study Tips")
# Category.new(title: "Job Search Tips")
# Category.new(title: "Women in Tech")
# Category.new(title: "Moms in Tech")
# Category.new(title: "Career")
# Category.new(title: "Kids")
# Category.new(title: "Diversity in Tech")
# Category.new(title: "Empathy")
# Category.new(title: "Authenticity")
# Category.new(title: "Growth")

Post.create(title: "I did it!", created: "March 15, 2019", content: "I'm excited to announce to my LinkedIn family that after two years of learning to code and this past year of intense coding, I have accepted a job offer to be a software engineer. Details to come. For all those months when I coded till my eyes shut most nights, typed out solutions to labs with one hand while my toddler sat on my lap, woke up early before everyone else to get in an hour of learning, and grabbed any moment of peace to learn more - naptimes, bus rides, weekends at my parents' where they watched her so I could code - it resulted in my life being changed and the beginning of a career I am going to love. I would have never believed, 3 years ago in South Korea as I prepared to move my family home to the US and give up a career in teaching, that this is where I'd be. I want to thank so many of you who are reading this. You have played a part in my journey, and I can't name you all - but if you believed in me, you played a part in making this possible. And for all you moms reading this, wondering if this could be possible for you - it can. I know it may seem out of reach, but it isn't. It takes sacrifices. It takes determination. But who better than moms know how to persevere?")
