Category.create(title: "Study Tips")
Category.create(title: "Job Search Tips")
Category.create(title: "Kids")
Category.create(title: "Diversity in Tech")
Category.create(title: "Motherhood")
Category.create(title: "Coding")
Category.create(title: "Career")
Category.create(title: "Side Projects")
Category.create(title: "Ruby on Rails")
Category.create(title: "JavaScript")
Category.create(title: "Other")
Category.create(title: "Learning to Code")
Category.create(title: "Reflections")
Category.create(title: "Women in Tech")
Category.create(title: "Mentors")
Category.create(title: "Events and Meetups")
Category.create(title: "Walkthroughs")
