Category.new(title: "Personal Story")
Category.new(title: "Learning to Code")
Category.new(title: "Happiness and Success")
Category.new(title: "Trying New Things")
Category.new(title: "Coding Tips")
Category.new(title: "Study Tips")
Category.new(title: "Job Search Tips")
Category.new(title: "Moms in Tech")
Category.new(title: "Kids")
Category.new(title: "Diversity in Tech")
Category.new(title: "Empathy")
Category.new(title: "Authenticity")
Category.new(title: "Growth")


Category.create(title: "Motherhood")
Category.create(title: "Coding")
Category.create(title: "Career")
Category.create(title: "Side Projects")
Category.create(title: "Ruby on Rails")
Category.create(title: "JavaScript")
Category.create(title: "Other")
Category.create(title: "Learning to Code")
Category.create(title: "Reflections")
Category.create(title: "Women in Tech")
Category.create(title: "Mentors")
Category.create(title: "Events and Meetups")
Category.create(title: "Walkthroughs")
